server:
  port: 23104
  tomcat:
    connection-timeout: 3600000
    # 上传文件最大值
    max-http-form-post-size: 4096MB
  compression:
    enabled: true
spring:
  servlet:
    multipart:
      # 上传文件最大值
      max-file-size: 4096MB
      max-request-size: 4096MB
  datasource:
    username: postgres
    password: postgres
#    password: postgis@2024a
#    url: jdbc:postgresql_postGIS://8.138.103.110:5432/gisdata
    url: jdbc:postgresql_postGIS://192.168.60.231:5432/gisdata
    driver-class-name: net.postgis.jdbc.DriverWrapper
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

easy-query:
  enable: true
  database: pgsql
  name-conversion: underlined
  delete-throw: false
  print-sql: true
  keep-native-style: true
