server:
  port: 23104
  tomcat:
    # 上传文件最大值
    max-http-form-post-size: 4096MB
spring:
  servlet:
    multipart:
      # 上传文件最大值
      max-file-size: 4096MB
      max-request-size: 4096MB
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql_postGIS://192.168.60.231:5432/gisdata
    driver-class-name: net.postgis.jdbc.DriverWrapper
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
